version: '3'

services:
  front-end:
    build:
      context: ../front-end
      dockerfile: ../front-end/front-end.dockerfile
    restart: always
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1

  back-end:
    build:
      context: ../back-end
      dockerfile: ../back-end/back-end.dockerfile
    restart: always
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1

  netease-music-api:
    image: longcat123/netease-music-api:1.0.0
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1

  