apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: muscoach-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: muscoach.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: muscoach-front-end
            port:
              number: 31807